### PR TITLE
Add Schneier "When Will We See Collisions for SHA-1?" ref

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by cgwalters** [comment]
oops, signed commit issues...let me try undoing.

@cgwalters-bot r- dec164b

**Comment by ypid** [comment]
Hm, signed commits might not work with all workflows. I am aware. I read quite a few things gpg signing and git the last days :wink:
Tell me when I should change something.

**Comment by cgwalters** [comment]
Nothing is wrong on your end, it's [Homu](https://github.com/servo/homu/) which is a commit merging bot that breaks badly with them...I need to debug it.

**Comment by cgwalters** [comment]
Merged, thanks!

**Comment by ypid** [comment]
You are most welcome. Thanks for the awesome project! Have been looking for this quite a while :wink:

**Pull request merged**
